services:
  mc-server:
    platform: linux/amd64
    build:
      context: .
    container_name: minecraft_bedrock_server
    ports:
      - "${SERVER_PORT:-19132}:${SERVER_PORT:-19132}/udp"
      - "${SERVER_PORTV6:-19133}:${SERVER_PORTV6:-19133}/udp"
    volumes:
      - ./config:/temp-config:rw
      - bedrock_data:/bedrock/:rw
    env_file:
      - .env
    restart: unless-stopped
volumes:
  bedrock_data: